### ISSUE TITLE
另一件事

### ISSUE THREAD

**Issue by sopy264** [wbs306/Action_OpenWrt_Xiaomi_R4AG#1]
昨天我发现了xaga代号的设备树，为何您又将其删了，无法正常工作咩awa

**Comment by wbs306** [comment]
hhhhhh, 之前因为弄砖了去售后换新, 需要等下个月才能解锁, 所以就先暂时设为私有, 现在device倒是基本写好了就差debug

**Comment by sopy264** [comment]
A(您有打算做rom包嘛，期待吃上您制作的类原生

**Comment by wbs306** [comment]
原生自然是会一直做的（如果没有再次变砖的话）这台机子本身就是想用来折腾，虽然它是联发科...

**Comment by sopy264** [comment]
说起来我有点好奇mtk设备的特殊性，为啥没有人折腾

**Comment by wbs306** [comment]
主要是不开源，加上没有像高通9008那样线刷方便吧，高通是挺难砖的

**Comment by sopy264** [comment]
目前看来似乎有些开发者需要那个仓库，也许您可以先将其开放，您的设备树似乎是唯一一颗，同时其他开发者也能通过其开发rom，debug并将修复后的树commit

**Comment by wbs306** [comment]
你们有交流群吗，正好我也想测试测试

**Comment by sopy264** [comment]
有一个500人的群，是另一个PEP的GSI的开发者的群聊，应该都是note11t pro用户，但是满了，我也没进去🌚

**Comment by sopy264** [comment]
如果你有需要的话我可以帮你测试

**Comment by wbs306** [comment]
噢那个群，我也没进去

**Comment by sopy264** [comment]
哈哈

**Comment by sopy264** [comment]
加个QQ吧2737287134
