### ISSUE TITLE
4A千兆版2.30.28不行

### ISSUE THREAD

**Issue by NorthBig** [wbs306/Action_OpenWrt_Xiaomi_R4AG#5]
刷进去了breed以后，使用了openwrt-ramips-mt7621-xiaomi_mi-router-4a-gigabit-v2-squashfs-sysupgrade和eeprom。刷一切正常，两个蓝灯灰暗（据说这个正常）。但是等了半天，电脑打不开192.168.1.1. 
我的设备：小米4A千兆版 2.30.28最新版本（按理说都是2.30，应该没问题呀，但是openwrt.org说V2不能刷OpenWRT？），Winbond的Flash芯片, MediaTek MT7603EN处理器,ESMT内存。其他好像都一样。
刷完以后，不能启动，进不去页面。CMD下面ping不通。
特此汇报。

**Comment by wbs306** [comment]
这个仓库里的不适合v2
